package com.example.turboautismdoselog.substances

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED FILE
 *
 * DO NOT EDIT MANUALLY.
 *
 * Generated by:
 *     tools/update_substances.py
 *
 * All data is sourced from PsychonautWiki (https://psychonautwiki.org),
 * licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/).
 * This app is not affiliated with or endorsed by PsychonautWiki.
 *
 * Source:
 *     PsychonautWiki GraphQL (Bifrost)
 *
 * Generated:
 *     2026-08-01 21:56:01 UTC
 * --------------------------------------------------------------------
 */

data class DurationRange(
    val minMinutes: Int?,
    val maxMinutes: Int?
)

data class RouteDuration(
    val route: String,
    val onset: DurationRange?,
    val comeup: DurationRange?,
    val peak: DurationRange?,
    val offset: DurationRange?,
    val total: DurationRange?,
    val afterglow: DurationRange?
)

data class KnownSubstance(
    val id: String,
    val name: String,
    val aliases: List<String>,
    val routes: List<RouteDuration>
)

object SubstanceDatabase {

    val substances = listOf(

        KnownSubstance(
            id = "1-3-butanediol",
            name = "1,3-Butanediol",
            aliases = listOf("DMT", "Dimethyltryptamine", "Dmitri", "2-(1H-Indol-3-yl)-N,N-dimethylethanamine"),
            routes = listOf(
                RouteDuration(
                    "oral",
                    DurationRange(null, null),
                    DurationRange(null, null),
                    DurationRange(null, null),
                    DurationRange(null, null),
                    DurationRange(null, null),
                    DurationRange(null, null)
                ),
                RouteDuration(
                    "sublingual",
                    DurationRange(null, null),
                    DurationRange(null, null),
                    DurationRange(null, null),
                    DurationRange(null, null),
                    DurationRange(null, null),
                    DurationRange(null, null)
                )
            )
        ),

        KnownSubstance(
            id = "1cp-mipla",
            name = "1cP-MiPLA",
            aliases = listOf("1cP-MiPLA"),
            routes = listOf(
                RouteDuration(
                    "oral",
                    DurationRange(20, 40),
                    DurationRange(45, 90),
                    DurationRange(60, 120),
                    DurationRange(60, 120),
                    DurationRange(240, 360),
                    null
                )
            )
        ),

        KnownSubstance(
            id = "1cp-al-lad",
            name = "1cP-AL-LAD",
            aliases = listOf("1cP-AL-LAD"),
            routes = listOf(
                RouteDuration(
                    "oral",
                    DurationRange(20, 60),
                    DurationRange(30, 60),
                    DurationRange(150, 300),
                    DurationRange(120, 180),
                    DurationRange(420, 600),
                    DurationRange(120, 1080)
                )
            )
        ),

        KnownSubstance(
            id = "1p-eth-lad",
            name = "1P-ETH-LAD",
            aliases = listOf("1P-ETH-LAD", "1-Propionyl-6-ethyl-6-nor-lysergic acid diethyamide"),
            routes = listOf(
                RouteDuration(
                    "oral",
                    DurationRange(30, 90),
                    null,
                    DurationRange(120, 240),
                    DurationRange(120, 240),
                    DurationRange(360, 720),
                    null
                )
            )
        ),

        KnownSubstance(
            id = "2-5-dma",
            name = "2,5-DMA",
            aliases = listOf("2,5-DMA", "DOH", "1-(2,5-dimethoxyphenyl)propan-2-amine"),
            routes = listOf(
                RouteDuration(
                    "oral",
                    null,
                    null,
                    null,
                    null,
                    DurationRange(360, 480),
                    null
                )
            )
        )

    )

    fun findById(id: String): KnownSubstance? =
        substances.find { it.id == id }

    fun findByName(query: String): KnownSubstance? {

        val normalized = query.trim().lowercase()

        return substances.find {

            it.name.lowercase() == normalized ||

                    it.aliases.any {
                        it.lowercase() == normalized
                    }
        }
    }
}
