import json
import re
from datetime import datetime

from models import DurationRange, RouteDuration, Substance


def make_id(name: str) -> str:
    """Generate a stable ID from the substance name."""

    value = name.lower()

    value = value.replace(",", "-")

    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value)

    return value.strip("-")


def duration_range_to_dict(value: DurationRange | None) -> dict | None:
    """Convert a DurationRange to a JSON-serializable dict."""

    if value is None:
        return None

    return {
        "minMinutes": value.min_minutes,
        "maxMinutes": value.max_minutes,
    }


def route_to_dict(route: RouteDuration) -> dict:
    """Convert one RouteDuration to a JSON-serializable dict."""

    return {
        "route": route.route,
        "onset": duration_range_to_dict(route.onset),
        "comeup": duration_range_to_dict(route.comeup),
        "peak": duration_range_to_dict(route.peak),
        "offset": duration_range_to_dict(route.offset),
        "total": duration_range_to_dict(route.total),
        "afterglow": duration_range_to_dict(route.afterglow),
    }


def substance_to_dict(substance: Substance) -> dict:
    """Convert one Substance to a JSON-serializable dict."""

    return {
        "id": make_id(substance.name),
        "name": substance.name,
        "aliases": substance.aliases,
        "routes": [route_to_dict(route) for route in substance.routes],
    }


def generate_database(substances: list[Substance]) -> str:
    """
    Generate the complete substances.json content as a string.
    """

    data = [substance_to_dict(substance) for substance in substances]

    return json.dumps(data, indent=2, ensure_ascii=False)


def generate_attribution() -> str:
    """
    Generate the attribution text file content.
    """

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    return f"""Substance duration data bundled with this app is sourced from
PsychonautWiki (https://psychonautwiki.org), licensed under
Creative Commons Attribution-ShareAlike 4.0 International
(CC BY-SA 4.0): https://creativecommons.org/licenses/by-sa/4.0/

This application is not affiliated with, endorsed by, or
officially connected to PsychonautWiki.

Generated by tools/update_substances.py via PsychonautWiki's
public GraphQL API (Bifrost).

Generated: {timestamp}
"""